name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Assure-toi que la version est correcte pour ton projet

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Met à jour pip
          pip install -r requirements.txt  # Installe les dépendances depuis requirements.txt
          pip install pytest coverage  # Installe pytest et coverage explicitement

      - name: Run tests
        run: |
          coverage run -m pytest  # Exécute pytest avec couverture de code
          coverage report  # Affiche le rapport de couverture
