name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche l'action lorsqu'il y a un push sur la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu pour l'exécution

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Vérifie le code du dépôt

    - name: Set up Python
      uses: actions/setup-python@v4  # Installe Python sur la machine virtuelle
      with:
        python-version: '3.11'  # Spécifie la version de Python à utiliser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installe toutes les dépendances nécessaires, y compris Sphinx et autres

    - name: Build the docs
      run: |
        make -f Makefile_Windows html  # Utilise le Makefile pour générer la documentation HTML

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Utilise l'action pour déployer sur GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html  # Spécifie le dossier où se trouvent les fichiers HTML générés